// <auto-generated />
using System;
using Bulgarikon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulgarikon.Data.Migrations
{
    [DbContext(typeof(BulgarikonDbContext))]
    [Migration("20260213075213_SeedInitialDataMigration")]
    partial class SeedInitialDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulgarikon.Data.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2b60789-5d1e-4b46-a7f8-8b4f6e9a9001"),
                            IsCorrect = true,
                            QuestionId = new Guid("ad61b324-9e5f-4b82-b7d2-3c8e1f4a8001"),
                            Text = "Траки"
                        },
                        new
                        {
                            Id = new Guid("03c7189a-6e2f-4c57-b9a1-9c5a7f1b9002"),
                            IsCorrect = false,
                            QuestionId = new Guid("ad61b324-9e5f-4b82-b7d2-3c8e1f4a8001"),
                            Text = "Викинги"
                        },
                        new
                        {
                            Id = new Guid("14d829ab-7f3a-4d68-81b2-ad6b8c2c9003"),
                            IsCorrect = false,
                            QuestionId = new Guid("ad61b324-9e5f-4b82-b7d2-3c8e1f4a8001"),
                            Text = "Ацтеки"
                        },
                        new
                        {
                            Id = new Guid("25e93abc-8a4b-4e79-92c3-be7c9d3d9004"),
                            IsCorrect = false,
                            QuestionId = new Guid("ad61b324-9e5f-4b82-b7d2-3c8e1f4a8001"),
                            Text = "Самураи"
                        },
                        new
                        {
                            Id = new Guid("36fa4bcd-9b5c-4f8a-a3d4-cf8d1e4e9005"),
                            IsCorrect = true,
                            QuestionId = new Guid("be72c435-1f6a-4c91-92e3-4d9f2a5b8002"),
                            Text = "Развитие на писменост и държавност"
                        },
                        new
                        {
                            Id = new Guid("47ab19c2-8d3f-4e91-a7c2-1f8e9b3d9006"),
                            IsCorrect = false,
                            QuestionId = new Guid("be72c435-1f6a-4c91-92e3-4d9f2a5b8002"),
                            Text = "Интернет и електронна търговия"
                        },
                        new
                        {
                            Id = new Guid("58bc2ad3-9e4f-4b82-b6d3-2a9f7c4e9007"),
                            IsCorrect = false,
                            QuestionId = new Guid("be72c435-1f6a-4c91-92e3-4d9f2a5b8002"),
                            Text = "Космически полети"
                        },
                        new
                        {
                            Id = new Guid("69cd3be4-1f5a-4c73-95e4-3b1a8d5f9008"),
                            IsCorrect = false,
                            QuestionId = new Guid("be72c435-1f6a-4c91-92e3-4d9f2a5b8002"),
                            Text = "Съвременни парламенти"
                        },
                        new
                        {
                            Id = new Guid("7ade4cf5-2a6b-4d64-a4f5-4c2b9e6a9009"),
                            IsCorrect = true,
                            QuestionId = new Guid("cf83d546-2a7b-4e13-a6f4-5e1c3b6d8003"),
                            Text = "Съхранява знание и улеснява управлението"
                        },
                        new
                        {
                            Id = new Guid("8bef5d06-3b7c-4e55-b3a6-5d3c1f7b9010"),
                            IsCorrect = false,
                            QuestionId = new Guid("cf83d546-2a7b-4e13-a6f4-5e1c3b6d8003"),
                            Text = "Замества земеделието"
                        },
                        new
                        {
                            Id = new Guid("91f06e17-4c8d-4f46-92b7-6e4d2a8c9011"),
                            IsCorrect = false,
                            QuestionId = new Guid("cf83d546-2a7b-4e13-a6f4-5e1c3b6d8003"),
                            Text = "Премахва нуждата от закони"
                        },
                        new
                        {
                            Id = new Guid("a2f17f28-5d9e-4a37-a1c8-7f5e3b9d9012"),
                            IsCorrect = false,
                            QuestionId = new Guid("cf83d546-2a7b-4e13-a6f4-5e1c3b6d8003"),
                            Text = "Забранява търговията"
                        },
                        new
                        {
                            Id = new Guid("b3f28a39-6e1f-4b28-b2d9-8a6f4c1e9013"),
                            IsCorrect = true,
                            QuestionId = new Guid("d094e657-3b8c-4f24-b7a5-6f2d4c7e8004"),
                            Text = "Площади, обществени сгради и пазари"
                        },
                        new
                        {
                            Id = new Guid("c4f39b4a-7f2a-4c19-83ea-9b7a5d2f9014"),
                            IsCorrect = false,
                            QuestionId = new Guid("d094e657-3b8c-4f24-b7a5-6f2d4c7e8004"),
                            Text = "Небостъргачи от стъкло"
                        },
                        new
                        {
                            Id = new Guid("d5f4ac5b-8a3b-4d10-94fb-ac8b6e3f9015"),
                            IsCorrect = false,
                            QuestionId = new Guid("d094e657-3b8c-4f24-b7a5-6f2d4c7e8004"),
                            Text = "Метро линии"
                        },
                        new
                        {
                            Id = new Guid("e6f5bd6c-9b4c-4e01-a5fc-bd9c7f4a9016"),
                            IsCorrect = false,
                            QuestionId = new Guid("d094e657-3b8c-4f24-b7a5-6f2d4c7e8004"),
                            Text = "Магистрали и летища"
                        },
                        new
                        {
                            Id = new Guid("f7a6ce7d-1c5d-4f92-b6ad-ce1d8a5b9017"),
                            IsCorrect = true,
                            QuestionId = new Guid("e1a5f768-4c9d-4a35-91e6-7a3e5d8f8005"),
                            Text = "681 г."
                        },
                        new
                        {
                            Id = new Guid("08b7df8e-2d6e-4a83-97be-df2e9b6c9018"),
                            IsCorrect = false,
                            QuestionId = new Guid("e1a5f768-4c9d-4a35-91e6-7a3e5d8f8005"),
                            Text = "1018 г."
                        },
                        new
                        {
                            Id = new Guid("19c8e09f-3e7f-4b74-a8cf-e03f1c7d9019"),
                            IsCorrect = false,
                            QuestionId = new Guid("e1a5f768-4c9d-4a35-91e6-7a3e5d8f8005"),
                            Text = "1185 г."
                        },
                        new
                        {
                            Id = new Guid("2ad9f1a0-4f8a-4c65-b9d0-f14a2d8e9020"),
                            IsCorrect = false,
                            QuestionId = new Guid("e1a5f768-4c9d-4a35-91e6-7a3e5d8f8005"),
                            Text = "1878 г."
                        },
                        new
                        {
                            Id = new Guid("3beaf2b1-508b-4d56-a1e1-02b3c4d5e621"),
                            IsCorrect = true,
                            QuestionId = new Guid("f2b60789-5d1e-4b46-a7f8-8b4f6e9a8006"),
                            Text = "Цар Симеон Велики"
                        },
                        new
                        {
                            Id = new Guid("4cfb03c2-619c-4e67-b2f2-13c4d5e6f732"),
                            IsCorrect = false,
                            QuestionId = new Guid("f2b60789-5d1e-4b46-a7f8-8b4f6e9a8006"),
                            Text = "Паисий Хилендарски"
                        },
                        new
                        {
                            Id = new Guid("5d0c14d3-72ad-4f78-c3a3-24d5e6f70843"),
                            IsCorrect = false,
                            QuestionId = new Guid("f2b60789-5d1e-4b46-a7f8-8b4f6e9a8006"),
                            Text = "Васил Левски"
                        },
                        new
                        {
                            Id = new Guid("6e1d25e4-83be-4a89-d4b4-35e6f7081944"),
                            IsCorrect = false,
                            QuestionId = new Guid("f2b60789-5d1e-4b46-a7f8-8b4f6e9a8006"),
                            Text = "Христо Ботев"
                        },
                        new
                        {
                            Id = new Guid("7f2e36f5-94cf-4b9a-e5c5-46f708192a55"),
                            IsCorrect = true,
                            QuestionId = new Guid("03c7189a-6e2f-4c57-b9a1-9c5a7f1b8007"),
                            Text = "1185 г."
                        },
                        new
                        {
                            Id = new Guid("802f47a6-a5d0-4c0b-f6d6-5708192b3b66"),
                            IsCorrect = false,
                            QuestionId = new Guid("03c7189a-6e2f-4c57-b9a1-9c5a7f1b8007"),
                            Text = "681 г."
                        },
                        new
                        {
                            Id = new Guid("913058b7-b6e1-4d1c-07e7-68192a3c4c77"),
                            IsCorrect = false,
                            QuestionId = new Guid("03c7189a-6e2f-4c57-b9a1-9c5a7f1b8007"),
                            Text = "1396 г."
                        },
                        new
                        {
                            Id = new Guid("a24069c8-c7f2-4e2d-18f8-792a3b4d5d88"),
                            IsCorrect = false,
                            QuestionId = new Guid("03c7189a-6e2f-4c57-b9a1-9c5a7f1b8007"),
                            Text = "330 г."
                        },
                        new
                        {
                            Id = new Guid("b3517ad9-d803-4f3e-29a9-8a3b4c5e6e99"),
                            IsCorrect = true,
                            QuestionId = new Guid("14d829ab-7f3a-4d68-81b2-ad6b8c2c8008"),
                            Text = "Иван Асен II"
                        },
                        new
                        {
                            Id = new Guid("c4628bea-e914-4a4f-3aba-9b4c5d6f7faa"),
                            IsCorrect = false,
                            QuestionId = new Guid("14d829ab-7f3a-4d68-81b2-ad6b8c2c8008"),
                            Text = "Кубрат"
                        },
                        new
                        {
                            Id = new Guid("d5739cfb-fa25-4b50-4bcb-ac5d6e7080bb"),
                            IsCorrect = false,
                            QuestionId = new Guid("14d829ab-7f3a-4d68-81b2-ad6b8c2c8008"),
                            Text = "Аспарух"
                        },
                        new
                        {
                            Id = new Guid("e684ad0c-0b36-4c61-5cdc-bd6e7f8191cc"),
                            IsCorrect = false,
                            QuestionId = new Guid("14d829ab-7f3a-4d68-81b2-ad6b8c2c8008"),
                            Text = "Крум"
                        },
                        new
                        {
                            Id = new Guid("f795be1d-1c47-4d72-6ded-ce7f8092a2dd"),
                            IsCorrect = true,
                            QuestionId = new Guid("25e93abc-8a4b-4e79-92c3-be7c9d3d8009"),
                            Text = "Априлско въстание"
                        },
                        new
                        {
                            Id = new Guid("08a6cf2e-2d58-4e83-7efe-df8091a3b3ee"),
                            IsCorrect = false,
                            QuestionId = new Guid("25e93abc-8a4b-4e79-92c3-be7c9d3d8009"),
                            Text = "Основаване на Рим"
                        },
                        new
                        {
                            Id = new Guid("19b7d03f-3e69-4f94-80a0-e091a2b4c4ff"),
                            IsCorrect = false,
                            QuestionId = new Guid("25e93abc-8a4b-4e79-92c3-be7c9d3d8009"),
                            Text = "Откриване на Америка"
                        },
                        new
                        {
                            Id = new Guid("2ac8e150-4f7a-4a05-91b1-f1a2b3c5d500"),
                            IsCorrect = false,
                            QuestionId = new Guid("25e93abc-8a4b-4e79-92c3-be7c9d3d8009"),
                            Text = "Френска революция"
                        },
                        new
                        {
                            Id = new Guid("3bd9f261-508b-4b16-a2c2-02b3c4d6e611"),
                            IsCorrect = true,
                            QuestionId = new Guid("36fa4bcd-9b5c-4f8a-a3d4-cf8d1e4e8010"),
                            Text = "1878 г."
                        },
                        new
                        {
                            Id = new Guid("4cea0372-619c-4c27-b3d3-13c4d5e7f722"),
                            IsCorrect = false,
                            QuestionId = new Guid("36fa4bcd-9b5c-4f8a-a3d4-cf8d1e4e8010"),
                            Text = "1396 г."
                        },
                        new
                        {
                            Id = new Guid("5dfb1483-72ad-4d38-c4e4-24d5e6f80833"),
                            IsCorrect = false,
                            QuestionId = new Guid("36fa4bcd-9b5c-4f8a-a3d4-cf8d1e4e8010"),
                            Text = "1018 г."
                        },
                        new
                        {
                            Id = new Guid("6e0c2594-83be-4e49-d5f5-35e6f7081934"),
                            IsCorrect = false,
                            QuestionId = new Guid("36fa4bcd-9b5c-4f8a-a3d4-cf8d1e4e8010"),
                            Text = "1453 г."
                        });
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CivilizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("EraId");

                    b.ToTable("Artifacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47ab19c2-8d3f-4e91-a7c2-1f8e9b3d1001"),
                            CivilizationId = new Guid("d1a57a73-e7af-4db9-a713-eea9b9f579e2"),
                            Description = "Ритуална златна маска, свързвана с тракийски погребални практики. Използвана като символ за богатство и статус.",
                            DiscoveredAt = new DateTime(2012, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EraId = new Guid("76164f60-cb04-400a-90f0-97203f0e420a"),
                            Location = "Тракия",
                            Material = "Злато",
                            Name = "Златна маска (символичен артефакт)",
                            Year = -400
                        },
                        new
                        {
                            Id = new Guid("58bc2ad3-9e4f-4b82-b6d3-2a9f7c4e1002"),
                            CivilizationId = new Guid("2f0c3a11-7b8e-4f6a-9d10-5c6b7a8e9002"),
                            Description = "Оръжие от ранното Средновековие. Използвано в бойни сблъсъци и като знак за воинска принадлежност.",
                            DiscoveredAt = new DateTime(2008, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Location = "Североизточна България",
                            Material = "Желязо",
                            Name = "Меч (ранносредновековен)",
                            Year = 800
                        },
                        new
                        {
                            Id = new Guid("69cd3be4-1f5a-4c73-95e4-3b1a8d5f1003"),
                            CivilizationId = new Guid("2f0c3a11-7b8e-4f6a-9d10-5c6b7a8e9002"),
                            Description = "Каменен надпис, свидетелстващ за административни и културни практики в българските земи през Средновековието.",
                            DiscoveredAt = new DateTime(1999, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Location = "Плиска",
                            Material = "Камък",
                            Name = "Каменен надпис",
                            Year = 900
                        },
                        new
                        {
                            Id = new Guid("7ade4cf5-2a6b-4d64-a4f5-4c2b9e6a1004"),
                            Description = "Пръстен-печат, използван за удостоверяване на документи и принадлежност към аристокрацията.",
                            DiscoveredAt = new DateTime(2015, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EraId = new Guid("471c687f-caef-4cf6-8a8b-3dad51058485"),
                            Location = "Търново",
                            Material = "Сребро",
                            Name = "Пръстен-печат",
                            Year = 1230
                        },
                        new
                        {
                            Id = new Guid("8bef5d06-3b7c-4e55-b3a6-5d3c1f7b1005"),
                            Description = "Керамичен съд от бита. Използван за съхранение на храни и течности, типичен за ежедневието на епохата.",
                            DiscoveredAt = new DateTime(2003, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EraId = new Guid("68a72d82-601f-49c1-821c-850a82646c21"),
                            Location = "Централна България",
                            Material = "Керамика",
                            Name = "Керамичен съд",
                            Year = 1700
                        });
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.BulgarikonUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Civilization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<Guid>("EraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EraId");

                    b.ToTable("Civilizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1a57a73-e7af-4db9-a713-eea9b9f579e2"),
                            Description = "Древно население на Балканите, оставило богато културно наследство и значими археологически находки.",
                            EndYear = 46,
                            EraId = new Guid("76164f60-cb04-400a-90f0-97203f0e420a"),
                            Name = "Траки",
                            StartYear = -1500,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("2f0c3a11-7b8e-4f6a-9d10-5c6b7a8e9002"),
                            Description = "Народ със степен произход, който участва в създаването на българската държава и оформянето на ранната българска народност.",
                            EndYear = 900,
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Name = "Прабългари",
                            StartYear = 600,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("f1a57a73-e7af-4db9-a713-eea9b9f579e2"),
                            Description = "Славянските племена се заселват на Балканите и имат ключова роля в етногенезиса и културата на региона.",
                            EndYear = 900,
                            EraId = new Guid("e1a57a73-e7af-4db9-a713-eea9b9f579e2"),
                            Name = "Славяни",
                            StartYear = 500,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ad1d6a1a-6122-420d-908b-55fbe5eb18ca"),
                            Description = "Източната Римска империя – доминираща сила в Източното Средиземноморие и важен съперник/партньор на България.",
                            EndYear = 1453,
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Name = "Византийска империя",
                            StartYear = 330,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("9f578916-414a-4d35-92b3-fbc187d382dd"),
                            Description = "Държавата, под чиято власт българските земи остават до Освобождението през 1878 г.",
                            EndYear = 1922,
                            EraId = new Guid("68a72d82-601f-49c1-821c-850a82646c21"),
                            Name = "Османска империя",
                            StartYear = 1299,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Era", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Eras");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76164f60-cb04-400a-90f0-97203f0e420a"),
                            Description = "Античността обхваща най-ранните периоди от човешката история и възхода на древните цивилизации. Характерна е с развитието на земеделие, градове, писменост и ранни форми на държавност.",
                            EndYear = 500,
                            Name = "Античност",
                            StartYear = -3000
                        },
                        new
                        {
                            Id = new Guid("e1a57a73-e7af-4db9-a713-eea9b9f579e2"),
                            Description = "Период на значителни миграции в Европа (IV–VII век), свързан с разместване на племена и народи и с упадъка на Западната Римска империя.",
                            EndYear = 700,
                            Name = "Велико преселение на народите",
                            StartYear = 300
                        },
                        new
                        {
                            Id = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Description = "Държавата, утвърдена след 681 г., се превръща във водеща сила на Балканите. Периодът е белязан от християнизацията и културния разцвет, особено при цар Симеон Велики.",
                            EndYear = 1018,
                            Name = "Първо българско царство",
                            StartYear = 681
                        },
                        new
                        {
                            Id = new Guid("471c687f-caef-4cf6-8a8b-3dad51058485"),
                            Description = "Възстановено през 1185 г., Второто българско царство преживява културен подем и териториално разширение, като значим владетел е цар Иван Асен II. Периодът завършва с османското завоевание.",
                            EndYear = 1396,
                            Name = "Второ българско царство",
                            StartYear = 1185
                        },
                        new
                        {
                            Id = new Guid("68a72d82-601f-49c1-821c-850a82646c21"),
                            Description = "Периодът на османска власт над българските земи (края на XIV век – 1878 г.) е време на дълбоки социални и културни промени, но и на съпротива и националноосвободителни движения.",
                            EndYear = 1878,
                            Name = "Османско владичество",
                            StartYear = 1396
                        });
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<Guid>("EraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EraId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91f06e17-4c8d-4f46-92b7-6e4d2a8c2001"),
                            Description = "През 680 г. хан Аспарух разгромява византийската армия на император Константин IV в укрепения лагер при Онгъла. Победата води до признаването на българската държава през 681 г.",
                            EndYear = 680,
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Location = "Онгъла (Северна Добруджа)",
                            StartYear = 680,
                            Title = "Битката при Онгъла"
                        },
                        new
                        {
                            Id = new Guid("a2f17f28-5d9e-4a37-a1c8-7f5e3b9d2002"),
                            Description = "Сражение, при което хан Крум нанася тежко поражение на византийците след похода на Никифор I.",
                            EndYear = 811,
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Location = "Върбишки проход",
                            StartYear = 811,
                            Title = "Битката във Върбишкия проход"
                        },
                        new
                        {
                            Id = new Guid("b3f28a39-6e1f-4b28-b2d9-8a6f4c1e2003"),
                            Description = "Превземането на столицата Търново от османците – ключов момент в падането на Второто българско царство.",
                            EndYear = 1393,
                            EraId = new Guid("471c687f-caef-4cf6-8a8b-3dad51058485"),
                            Location = "Търново",
                            StartYear = 1393,
                            Title = "Падането на Търново"
                        },
                        new
                        {
                            Id = new Guid("c4f39b4a-7f2a-4c19-83ea-9b7a5d2f2004"),
                            Description = "Въстание срещу османската власт, което предизвиква международен отзвук и подкрепя каузата за освобождение.",
                            EndYear = 1876,
                            EraId = new Guid("68a72d82-601f-49c1-821c-850a82646c21"),
                            Location = "Българските земи",
                            StartYear = 1876,
                            Title = "Априлско въстание"
                        },
                        new
                        {
                            Id = new Guid("d5f4ac5b-8a3b-4d10-94fb-ac8b6e3f2005"),
                            Description = "Обединяване на Княжество България и Източна Румелия – ключов акт за националното обединение.",
                            EndYear = 1885,
                            EraId = new Guid("68a72d82-601f-49c1-821c-850a82646c21"),
                            Location = "Пловдив",
                            StartYear = 1885,
                            Title = "Съединението на България"
                        });
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.EventCivilization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("EventId");

                    b.ToTable("EventCivilizations");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.EventFigure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FigureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("FigureId");

                    b.ToTable("EventFigures");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Figure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<Guid?>("CivilizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("EraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("EraId");

                    b.ToTable("Figures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6f5bd6c-9b4c-4e01-a5fc-bd9c7f4a3001"),
                            BirthYear = 640,
                            CivilizationId = new Guid("2f0c3a11-7b8e-4f6a-9d10-5c6b7a8e9002"),
                            DeathYear = 701,
                            Description = "Основател на Дунавска България. Свързан с утвърждаването на българската държава на Балканите.",
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Name = "Хан Аспарух"
                        },
                        new
                        {
                            Id = new Guid("f7a6ce7d-1c5d-4f92-b6ad-ce1d8a5b3002"),
                            BirthYear = 864,
                            DeathDate = new DateTime(927, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathYear = 927,
                            Description = "Владетел, при когото България достига значителен политически и културен подем (Златен век).",
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Name = "Цар Симеон I Велики"
                        },
                        new
                        {
                            Id = new Guid("2ad9f1a0-4f8a-4c65-b9d0-f14a2d8e3005"),
                            BirthYear = 1168,
                            DeathYear = 1207,
                            Description = "Владетел на Второто българско царство. Провежда активна външна политика и укрепва държавата.",
                            EraId = new Guid("471c687f-caef-4cf6-8a8b-3dad51058485"),
                            Name = "Цар Калоян"
                        },
                        new
                        {
                            Id = new Guid("08b7df8e-2d6e-4a83-97be-df2e9b6c3003"),
                            BirthDate = new DateTime(1837, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthYear = 1837,
                            DeathDate = new DateTime(1873, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathYear = 1873,
                            Description = "Апостол на свободата. Организатор на вътрешната революционна мрежа за освобождението на България.",
                            EraId = new Guid("68a72d82-601f-49c1-821c-850a82646c21"),
                            Name = "Васил Левски"
                        },
                        new
                        {
                            Id = new Guid("19c8e09f-3e7f-4b74-a8cf-e03f1c7d3004"),
                            BirthDate = new DateTime(1848, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthYear = 1848,
                            DeathDate = new DateTime(1876, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathYear = 1876,
                            Description = "Поет и революционер. Символ на борбата за национално освобождение през Възраждането.",
                            EraId = new Guid("68a72d82-601f-49c1-821c-850a82646c21"),
                            Name = "Христо Ботев"
                        });
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CivilizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FigureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("EraId");

                    b.HasIndex("EventId");

                    b.HasIndex("FigureId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad61b324-9e5f-4b82-b7d2-3c8e1f4a8001"),
                            QuizId = new Guid("5e16b7c8-1d9f-4a72-83e4-9f2c7b1d7001"),
                            Text = "Кое население е сред древните обитатели на Балканите?"
                        },
                        new
                        {
                            Id = new Guid("be72c435-1f6a-4c91-92e3-4d9f2a5b8002"),
                            QuizId = new Guid("5e16b7c8-1d9f-4a72-83e4-9f2c7b1d7001"),
                            Text = "Коя е една характерна черта на античните цивилизации?"
                        },
                        new
                        {
                            Id = new Guid("cf83d546-2a7b-4e13-a6f4-5e1c3b6d8003"),
                            QuizId = new Guid("6f27c8d9-3a5e-4b91-a6f2-1d8c7e2b7002"),
                            Text = "Какво е значението на писмеността за древните общества?"
                        },
                        new
                        {
                            Id = new Guid("d094e657-3b8c-4f24-b7a5-6f2d4c7e8004"),
                            QuizId = new Guid("6f27c8d9-3a5e-4b91-a6f2-1d8c7e2b7002"),
                            Text = "Кое е типично за античната градска култура?"
                        },
                        new
                        {
                            Id = new Guid("e1a5f768-4c9d-4a35-91e6-7a3e5d8f8005"),
                            QuizId = new Guid("7a38d9e1-6b2c-4f83-b7d1-4e9c2f3a7003"),
                            Text = "Коя година традиционно се приема за начало на българската държава?"
                        },
                        new
                        {
                            Id = new Guid("f2b60789-5d1e-4b46-a7f8-8b4f6e9a8006"),
                            QuizId = new Guid("7a38d9e1-6b2c-4f83-b7d1-4e9c2f3a7003"),
                            Text = "Кой владетел е свързан с културния разцвет през Златния век?"
                        },
                        new
                        {
                            Id = new Guid("03c7189a-6e2f-4c57-b9a1-9c5a7f1b8007"),
                            QuizId = new Guid("8b49e1f2-7c3d-4a92-91e8-5f2a7d3c7004"),
                            Text = "Коя година се свързва с възстановяването на българската държава (1185)?"
                        },
                        new
                        {
                            Id = new Guid("14d829ab-7f3a-4d68-81b2-ad6b8c2c8008"),
                            QuizId = new Guid("8b49e1f2-7c3d-4a92-91e8-5f2a7d3c7004"),
                            Text = "Кой владетел е свързан с разширение и подем на Второто царство?"
                        },
                        new
                        {
                            Id = new Guid("25e93abc-8a4b-4e79-92c3-be7c9d3d8009"),
                            QuizId = new Guid("9c5af213-8d4e-4c71-a3f9-6b1e2d7f7005"),
                            Text = "Кое събитие е част от националноосвободителните борби?"
                        },
                        new
                        {
                            Id = new Guid("36fa4bcd-9b5c-4f8a-a3d4-cf8d1e4e8010"),
                            QuizId = new Guid("9c5af213-8d4e-4c71-a3f9-6b1e2d7f7005"),
                            Text = "Коя година е Освобождението на България?"
                        });
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EraId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e16b7c8-1d9f-4a72-83e4-9f2c7b1d7001"),
                            EraId = new Guid("76164f60-cb04-400a-90f0-97203f0e420a"),
                            Title = "Античност: основни знания"
                        },
                        new
                        {
                            Id = new Guid("6f27c8d9-3a5e-4b91-a6f2-1d8c7e2b7002"),
                            EraId = new Guid("76164f60-cb04-400a-90f0-97203f0e420a"),
                            Title = "Античност: култура и общество"
                        },
                        new
                        {
                            Id = new Guid("7a38d9e1-6b2c-4f83-b7d1-4e9c2f3a7003"),
                            EraId = new Guid("c5c979ed-aead-4f32-8c53-36218218fbbd"),
                            Title = "Първо българско царство: ключови факти"
                        },
                        new
                        {
                            Id = new Guid("8b49e1f2-7c3d-4a92-91e8-5f2a7d3c7004"),
                            EraId = new Guid("471c687f-caef-4cf6-8a8b-3dad51058485"),
                            Title = "Второ българско царство: владетели и събития"
                        },
                        new
                        {
                            Id = new Guid("9c5af213-8d4e-4c71-a3f9-6b1e2d7f7005"),
                            EraId = new Guid("68a72d82-601f-49c1-821c-850a82646c21"),
                            Title = "Османско владичество: борби и възраждане"
                        });
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.QuizResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Answer", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Artifact", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Civilization", "Civilization")
                        .WithMany("Artifacts")
                        .HasForeignKey("CivilizationId");

                    b.HasOne("Bulgarikon.Data.Models.Era", "Era")
                        .WithMany("Artifacts")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Civilization");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Civilization", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Era", "Era")
                        .WithMany("Civilizations")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Event", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Era", "Era")
                        .WithMany("Events")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.EventCivilization", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Civilization", "Civilization")
                        .WithMany("EventCivilizations")
                        .HasForeignKey("CivilizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bulgarikon.Data.Models.Event", "Event")
                        .WithMany("EventCivilizations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Civilization");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.EventFigure", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Event", "Event")
                        .WithMany("EventFigures")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bulgarikon.Data.Models.Figure", "Figure")
                        .WithMany("EventFigures")
                        .HasForeignKey("FigureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Figure");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Feedback", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.BulgarikonUser", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Figure", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Civilization", "Civilization")
                        .WithMany("Figures")
                        .HasForeignKey("CivilizationId");

                    b.HasOne("Bulgarikon.Data.Models.Era", "Era")
                        .WithMany("Figures")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Civilization");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Image", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Artifact", null)
                        .WithMany("Images")
                        .HasForeignKey("ArtifactId");

                    b.HasOne("Bulgarikon.Data.Models.Civilization", "Civilization")
                        .WithMany("Images")
                        .HasForeignKey("CivilizationId");

                    b.HasOne("Bulgarikon.Data.Models.Era", "Era")
                        .WithMany("Images")
                        .HasForeignKey("EraId");

                    b.HasOne("Bulgarikon.Data.Models.Event", "Event")
                        .WithMany("Images")
                        .HasForeignKey("EventId");

                    b.HasOne("Bulgarikon.Data.Models.Figure", "Figure")
                        .WithMany("Images")
                        .HasForeignKey("FigureId");

                    b.Navigation("Civilization");

                    b.Navigation("Era");

                    b.Navigation("Event");

                    b.Navigation("Figure");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Question", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Quiz", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Era", "Era")
                        .WithMany("Quizzes")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.QuizResult", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bulgarikon.Data.Models.BulgarikonUser", "User")
                        .WithMany("QuizResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.BulgarikonUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.BulgarikonUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bulgarikon.Data.Models.BulgarikonUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Bulgarikon.Data.Models.BulgarikonUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Artifact", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.BulgarikonUser", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("QuizResults");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Civilization", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("EventCivilizations");

                    b.Navigation("Figures");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Era", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Civilizations");

                    b.Navigation("Events");

                    b.Navigation("Figures");

                    b.Navigation("Images");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Event", b =>
                {
                    b.Navigation("EventCivilizations");

                    b.Navigation("EventFigures");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Figure", b =>
                {
                    b.Navigation("EventFigures");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Bulgarikon.Data.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
